const events = {
    'react-workshop-2024': {
      title: 'React Workshop',
      date: 'March 15, 2024',
      time: '2:00 PM - 5:00 PM',
      location: 'Computer Lab A',
      attendees: 45,
      maxAttendees: 60,
      description: 'Learn React fundamentals and build your first component',
      longDescription: 'Join us for an intensive React workshop where you\'ll learn the fundamentals of React development. This hands-on session will cover components, state management, props, and event handling. By the end of this workshop, you\'ll have built your first React application and gained the confidence to continue your React journey.',
      type: 'Workshop',
      image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      instructor: 'Sarah Chen',
      instructorRole: 'Senior React Developer',
      instructorImage: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&dpr=1',
      prerequisites: ['Basic JavaScript knowledge', 'HTML/CSS fundamentals', 'Code editor installed'],
      agenda: [
        { time: '2:00 PM - 2:30 PM', topic: 'Introduction to React' },
        { time: '2:30 PM - 3:15 PM', topic: 'Components and JSX' },
        { time: '3:15 PM - 3:30 PM', topic: 'Break' },
        { time: '3:30 PM - 4:15 PM', topic: 'State and Props' },
        { time: '4:15 PM - 5:00 PM', topic: 'Building Your First App' },
      ],
      tags: ['React', 'JavaScript', 'Frontend', 'Beginner'],
      price: 'Free',
      registrationDeadline: 'March 13, 2024',
    },
    'coding-bootcamp-2024': {
      title: 'Coding Bootcamp',
      date: 'March 22, 2024',
      time: '10:00 AM - 4:00 PM',
      location: 'Main Auditorium',
      attendees: 120,
      maxAttendees: 150,
      description: 'Intensive full-day coding session with industry experts',
      longDescription: 'A comprehensive full-day bootcamp designed to accelerate your coding skills. Work alongside industry experts and fellow developers on real-world projects. This intensive session covers multiple programming languages, best practices, and career guidance.',
      type: 'Bootcamp',
      image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      instructor: 'Alex Johnson',
      instructorRole: 'Full Stack Developer',
      instructorImage: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&dpr=1',
      prerequisites: ['Basic programming knowledge', 'Laptop with development environment', 'Enthusiasm to learn'],
      agenda: [
        { time: '10:00 AM - 11:30 AM', topic: 'Modern Development Practices' },
        { time: '11:30 AM - 12:00 PM', topic: 'Break' },
        { time: '12:00 PM - 1:00 PM', topic: 'Hands-on Project Work' },
        { time: '1:00 PM - 2:00 PM', topic: 'Lunch Break' },
        { time: '2:00 PM - 3:30 PM', topic: 'Advanced Techniques' },
        { time: '3:30 PM - 4:00 PM', topic: 'Career Guidance & Q&A' },
      ],
      tags: ['Full Stack', 'Career', 'Intensive', 'All Levels'],
      price: 'Free',
      registrationDeadline: 'March 20, 2024',
    },
    'ai-ml-hackathon-2024': {
      title: 'AI/ML Hackathon',
      date: 'March 29, 2024',
      time: '9:00 AM - 9:00 PM',
      location: 'Innovation Hub',
      attendees: 80,
      maxAttendees: 100,
      description: 'Build intelligent solutions in 12 hours',
      longDescription: 'Challenge yourself in our AI/ML hackathon! Teams will have 12 hours to build innovative solutions using artificial intelligence and machine learning. Mentors will be available throughout the event, and exciting prizes await the winners.',
      type: 'Hackathon',
      image: 'https://images.pexels.com/photos/3184293/pexels-photo-3184293.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      instructor: 'Dr. Emma Wilson',
      instructorRole: 'AI Research Scientist',
      instructorImage: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&dpr=1',
      prerequisites: ['Python programming', 'Basic ML knowledge', 'Team of 2-4 members'],
      agenda: [
        { time: '9:00 AM - 9:30 AM', topic: 'Registration & Team Formation' },
        { time: '9:30 AM - 10:00 AM', topic: 'Problem Statement Release' },
        { time: '10:00 AM - 6:00 PM', topic: 'Hacking Time' },
        { time: '6:00 PM - 8:00 PM', topic: 'Project Presentations' },
        { time: '8:00 PM - 9:00 PM', topic: 'Judging & Awards' },
      ],
      tags: ['AI', 'Machine Learning', 'Competition', 'Advanced'],
      price: 'Free',
      registrationDeadline: 'March 27, 2024',
    },
  };

  export default events;

export type EventType = keyof typeof events;